### ISSUE TITLE
using async handlers for ok()?

### ISSUE THREAD

**Issue by niv** [andreaferretti/rosencrantz#1]
Hey,

Playing around with this lib and loving the compose pattern. :)

I have a usage question though: How can you respond to handlers with async procs, so that they don't block the server?

Example:

``` nim
proc myAsyncBackend*(data...): Future[bool] {.async.} = true

handler = get[path("/test")[
  let resp = await myAsyncBackend(..)
  if resp: ok("yay") else: complete(Http403, "boo")
]]
```

Cheers!

**Comment by andreaferretti** [comment]
Good question! :-)

The way to go would be to define a custom handler, that is, a function with signature

``` nim
proc h(req: ref Request, ctx: Context): Future[Context]
```

Naturally, this is a little inconvenient. What I was thinking to do:
- define a template to avoid the boilerplate of repeating the signature everywhere
- improve the integration with existing handlers.

Let me explain the second sentence. Right now, `ok`, `complete` and so on return handlers, that is, functions of the type above. As such, they are not usable **inside** another handler, because that has to return a `Future[Context]`. That is, one cannot just do

``` nim
handler = get[path("/test")[
  proc(req: ref Request, ctx: Context): Future[Context] {.async.} =
    let resp = await myAsyncBackend(..)
    if resp: ok("yay") else: complete(Http403, "boo")
]]
```

because the return type is wrong. But there is an obvious way to convert a function with signature

``` nim
proc h(req: ref Request, ctx: Context): Future[Handler]
```

into a handler. (If you are familiar with functional programming, functions of type `(req: ref Request, ctx: Context) => Future[A]` form a monad.)

I will see whether the best course of action is to provide a converter or something else. In the end I would like to be able to write

``` nim
handler = get[path("/test")[
  handle:
    let resp = await myAsyncBackend(..)
    if resp: ok("yay") else: complete(Http403, "boo")
]]
```

or something like that.

Having done that, I should also be able to simplify some of the existing handlers.

In a couple of days, though, I will be on holidays for a week, so I will keep you updated when I come back.

**Comment by niv** [comment]
Some templates to make it work that easily would be nice. I'm already doing custom handlers for various stuff, (and I tried making a handler per path), but it really is rather elaborate and I can't be bothered to do this for all endpoints! That said, I'm just sticking to non-async stuff, so it's slow and slower. I'll be patient to see whatever you come up with :)

> Having done that, I should also be able to simplify some of the existing handlers.

That sounds great. While you're at it, maybe add something to extract the request object? Example usecase from actual app:

``` nim
proc getRequest*(p: proc(req: ref Request): Handler): Handler =
  proc h(req: ref Request, ctx: Context): Future[Context] {.async.} =
    let handler = p(req)
    return (await handler(req, ctx))

  return h
...
  post [path("/register")[ jsonBody(proc(body: JsonNode): Handler =
    let email = body.getStringParam("email")

    getRequest(proc (r: ref Request): Handler =
      ok waitFor(apiRegisterServer(r.hostname, email))
    )
  )]] ~
```

This still looks needlessly verbose to me, but I'm context-switching to rubyland all the time, so I'm rather spoiled on concise syntax.

Also maybe useful ('m just copy/pasting code here now, maybe it'll give you some good ideas):
- Catch typed errors (to not let them fall through)

``` nim
proc exceptionHandler(ha: Handler): auto =
  proc h(req: ref Request, ctx: Context): Future[Context] {.async.} =
    let ret = ha(req, ctx)

    if ret.failed:
      let msg = ret.error.msg.split("\n")[0]

      if ret.error of ParamError:
        let errstr = makeError("missing or invalid parameter: " & msg)
        await req[].respond(Http400, errstr, newStringTable())

      # elif ret.error of UnauthorizedError:
      #   let errstr = makeError("access denied: " & msg)
      #   await req[].respond(Http403, errstr, newStringTable())

      elif ret.error of OpDeniedError:
        let errstr = makeError("operation denied: " & msg)
        await req[].respond(Http403, errstr, newStringTable())

      elif ret.error of OpFailedError:
        let errstr = makeError("operation failed: " & msg)
        await req[].respond(Http500, errstr, newStringTable())

      else:
        error ret.error.msg
        # when defined(release):
        await req[].respond(Http500, $Http500, newStringTable())
        # else:
        #   await req[].respond(Http500, ret.error.msg, newStringTable())
      return

    await ret

  return h
```
- Logging

``` nim
proc loggingHandler(ha: Handler): auto =
  proc h(req: ref Request, ctx: Context): Future[Context] {.async.} =
    let ret = ha(req, ctx)
    debug "$3 $1 $2".format(req.reqMethod, req.url.path, req.hostname)
    await ret
  return h
```

> In a couple of days, though, I will be on holidays for a week, so I will keep you updated when I come back.

Enjoy your holidays :)

**Comment by andreaferretti** [comment]
Hi @niv thank you for your great suggestions!

In fact, the idea would be to be able to avoid to write custom handlers most of the time, but as you observed we are a little far from this at the moment.

I will certainly add more handlers as time permits, including the ones you suggest. After all, the fact that they are composable means that one does not pay for the features that are not used, so I am not very much worried about the possible proliferation of handlers.

**Comment by andreaferretti** [comment]
Hi @niv, I have started adding some support for custom handlers. I have added your `getRequest` and `logging` procedures, as well as a small `scope` template that can be used to write a little logic inline.

I have still to figure out how to handle errors, and a way to write a template that works similar to `scope` but deals with async procedures. Ideally, I would like to use it internally to simplify  a few of the existing handlers as well.

For the moment, I have released 0.1.2 with these few additions. Once I have the other stuff and something for the multipart forms, I would like to release version 0.2.0.

By the way, if you want to contribute, PR are very much welcome! :-)

**Comment by andreaferretti** [comment]
I have also added a `makeHandler` macro that is a first step towards writing custom handlers in a  simple way. Let me know any feedback you may have!

**Comment by niv** [comment]
Hey, that's lovely! Thanks for picking up on my trifly little feature requests!

I haven't had a chance yet to test it on my small web app, but I will soon. A small sidenote, when glancing over the commits: the logging handler should at least print out the result code from the handled request - and maybe shove it into logging.debug for 200/300, 400 into info, 500 into error? That of course presumes there's a working error handler installed. :) But as it stands now, everyone will want to write their own anyways.

I'll definitely keep watching this and let you know when I get back to messing with it. I'm sure I'll have better feedback then once I get to use the new toys.

**Comment by andreaferretti** [comment]
I have also added a `scopeAsync` template, that works like `scope`, but allows asynchronous operations in it.

I am about to release 0.2.0. I will add much improved logging (and CORS support) for 0.3.0.

**Comment by andreaferretti** [comment]
Hi @niv , I don't know if you are still interested, but I have also added improvements to logging, as you can see in the README.

Still not perfect by a long shot, but a little more flexible than it was before

**Comment by niv** [comment]
Hey!

Yeah, I'm still interested, but nim took a backseat to other projects.  I'll definitely get back to this, though I cannot promise exactly when.

I had a brief glance over the handler code and it looked well done and very usable.  My intended usecase is to just write small http/json service APIs with this, so CORS will come in handy too.

**Comment by andreaferretti** [comment]
I am closing this issue, since the things that were discussed here have eventually been implemented.

Please, if you need more functionality feel free to open another issue!
