### ISSUE TITLE
Streaming responses

### ISSUE THREAD

**Issue by andreaferretti** [andreaferretti/rosencrantz#11]
Especially for returning large files

**Comment by andreaferretti** [comment]
Done for large files, still to do in general

**Comment by s0kil** [comment]
@andreaferretti Any update on this feature?

**Comment by andreaferretti** [comment]
As mentioned, streaming files support is already available using [fileAsync](https://github.com/andreaferretti/rosencrantz/blob/master/rosencrantz/staticsupport.nim#L40).

I still have to implement a more general solution which works for [FutureStream](https://nim-lang.org/docs/asyncstreams.html) - which did not exist at the time this issue was opened. It should be rather easy, I will look into it
