### ISSUE TITLE
Crash on d:release

### ISSUE THREAD

**Issue by sclee15** [andreaferretti/rosencrantz#14]
thank you for such an interesting project.

Please check out following snippet

```
import asynchttpserver, asyncdispatch, rosencrantz, json

let handler = get[
    path("/")[
        scope do:
            let x = %*{"hello": "world"}
            return ok(x)
    ]
]

let server = newAsyncHttpServer()
waitFor server.serve(Port(8085), handler)
```

it runs with no problem without d:release
i used wrk -c 200 -t 2 http://localhost:8085
but after d:release applied, i  get "SIGSEGV: Illegal storage access. (Attempt to read from nil?)"
it is release mode so there's no stack trace

i hope it is a valid bug so you can catch it lator :)

**Comment by andreaferretti** [comment]
I am finding the same result. I am not sure what is going on: wrk is able to connect for a while and then everything crashes. I will let you know as soon as I find out what's wrong.

Also, it seems erratic: about half of the times, the server does not crash

**Comment by sclee15** [comment]
This stack and line tracking information could be helpful.

asyncdispatch.nim(1069)  waitFor
asyncdispatch.nim(1104)  poll
asyncdispatch.nim(176)   processPendingCallbacks
asyncmacro.nim(34)       cb
asynchttpserver.nim(217) processClientIter
asyncmacro.nim(370)      server
asyncmacro.nim(34)       cb
core.nim(82)             serverIter
assign.nim(96)           genericAssign
assign.nim(85)           genericAssignAux
assign.nim(24)           genericAssignAux
assign.nim(21)           genericAssignAux
assign.nim(85)           genericAssignAux
assign.nim(24)           genericAssignAux
assign.nim(21)           genericAssignAux
assign.nim(54)           genericAssignAux
gc.nim(494)              newObjNoInit
alloc.nim(531)           rawAlloc

**Comment by andreaferretti** [comment]
@sclee15 I am trying to investigate. How did you produce the stack trace in release mode?

**Comment by sclee15** [comment]
--stackTrace:on with release mode

**Comment by andreaferretti** [comment]
Ok thank you

**Comment by andreaferretti** [comment]
With latest Nim, the error appears [at this line](https://github.com/nim-lang/Nim/blob/devel/lib/system/alloc.nim#L563)

**Comment by andreaferretti** [comment]
Seems fixed by https://github.com/nim-lang/Nim/commit/c65ff403b27e1655504298ea65457cf1e00f4ebd

**Comment by andreaferretti** [comment]
It was a problem with Nim GC - it is fixed by now (at least, I have not been able to reproduce it)
