### ISSUE TITLE
Properly Parsing a Form

### ISSUE THREAD

**Issue by s0kil** [andreaferretti/rosencrantz#16]
I'm having trouble parsing a form.
### Here Is the handler:
```nim
post[
    path("/api/contact")[
      formBody(proc(form: StringTableRef): auto =
        echo form
        ok("Form")
      )
    ]
  ]
```
### Here is the output from `echo form`:
```nim
{------WebKitFormBoundaryb2NDKUkTY9ZiqSk9
Content-Disposition: form-data; name: "customerName"

User Name
------WebKitFormBoundaryb2NDKUkTY9ZiqSk9
Content-Disposition: form-data; name="customerEmail"

test@example.com
------WebKitFormBoundaryb2NDKUkTY9ZiqSk9
Content-Disposition: form-data; name="customerPhone"

3458769089
------WebKitFormBoundaryb2NDKUkTY9ZiqSk9
Content-Disposition: form-data; name="customerMessage"

Test Message
------WebKitFormBoundaryb2NDKUkTY9ZiqSk9--
}
```
When I try to access a value using `form["customerName"]` similar to [tests/server.nim](https://github.com/andreaferretti/rosencrantz/blob/master/tests/server.nim#L274) it fails and the server returns a 404.

Any help is very much appreciated.

**Comment by andreaferretti** [comment]
It looks like a mulitpart form and not a url-encoded form, you can use [multipart](https://github.com/andreaferretti/rosencrantz/blob/master/rosencrantz/formsupport.nim#L202) for that
