### ISSUE TITLE
`->` should take precedence over `~`

### ISSUE THREAD

**Issue by moigagoo** [andreaferretti/rosencrantz#6]
Consider the following code sample:

``` nim
import asyncdispatch, asynchttpserver
import rosencrantz

let handler =
  get[
    path("/api")[
      ok("Welcome to API")
    ]
  ] ~
  get[
    path("/api/version")[
      ok("0.0.1")
    ]
  ]

when isMainModule:
  let server = newAsyncHttpServer()
  waitFor server.serve(Port(8080), handler)
```

It works perfectly OK, with both `/api` and `/api/version` working.

However, if we rewrite it from `[]` to `->`, it breaks:

``` nim
import asyncdispatch, asynchttpserver
import rosencrantz

let handler =
  get -> path("/api") -> ok("Welcome to API") ~
  get -> path("/api/version") -> ok("0.0.1")

when isMainModule:
  let server = newAsyncHttpServer()
  waitFor server.serve(Port(8080), handler)
```

Only `/api`, i.e. the top route, matches.

This is counterintuitive and can be fixed by setting the priority of `->` operator higher than of `~`.

**Comment by moigagoo** [comment]
However, there's a dead simple workaround for it: just put each route in parens :-)

Still, I think it'd be better to have it work without the parens.

**Comment by andreaferretti** [comment]
Yes, when composing larger routes I always use `[]`.

I use `->` just when composing smaller handlers and assing them to a variable, and I want to fit them onto a single line.

In any case, I would be happy to fix the priority, but I confess I don't know how to set priority of operators in Nim :-D

**Comment by andreaferretti** [comment]
Apparently, precedence order is builtin http://nim-lang.org/docs/manual.html#syntax-precedence

**Comment by moigagoo** [comment]
It seems like the best way to fix this issue is by mentioning this behavior in the docs :-)
