### ISSUE TITLE
Use relative paths for imports

### ISSUE THREAD

**Issue by Varriount** [andreaferretti/rosencrantz#7]
Would there be any problem with changing all the imports to be relative to the main file ('../rosenrantz/handlers' instead of 'rosencrantz/handlers'? The current scheme prevents simple 'nim c rosencrantz' compilation, and confuses IDE tools such as nimsuggest.

**Comment by andreaferretti** [comment]
Not really, as long as this does not break anything for projects import rosencrantz via nimble. I will try and make this change. By the way, wouldn't it be better to import `'./handlers'` instead of `../rosencrantz/handlers'`?

**Comment by Varriount** [comment]
Probably. The one I suggested was just the first thing that came to mind.

**Comment by andreaferretti** [comment]
Done in 0.2.1
