### ISSUE TITLE
Why the Apache License?

### ISSUE THREAD

**Issue by lbmn** [andreaferretti/rosencrantz#9]
Dear Nim Contributor,

I am promoting Nim as (among its many other virtues) the programming language with the most unencumbered clear no-hassle no-lawyers-needed permissively-licensed ecosystem.  Currently [89.25%](https://github.com/lbmn/nim/tree/master/lice) of nimble packages fit the [copyfree.org](http://copyfree.org/) definition of Free Software, compared to 81% in runner-up cabal (Haskell) or for example 64% for npm (NodeJS).  I honestly believe that further improving on this distinction will contribute positively to Nim's future popularity growth.

Towards this end, I would very much like to initiate a dialogue with contributors to the Nim ecosystem who choose licenses that do not fit the Copyfree Standard.  The Apache License definitely isn't the most restrictive license out there, but it has the imperfections listed on the copyfree.org's [Rejected Licenses](http://copyfree.org/standard/rejected) page:
- Section 4, subsections 2 and 4 of the Apache License 2.0 violate point 3 ("Free Modification and Derivation") of the [Copyfree Standard Definition](http://copyfree.org/standard) by specifying conditions (beyond licensing) that must apply to modifications.

Currently 79% of nimble packages use the MIT license (which is what nimble recommends), the same license as Nim itself.  I personally plan to use the [Unlicense](https://en.wikipedia.org/wiki/Public-domain_software#Public-domain-like_licenses_and_waivers) for all my works, but any license on [the copyfree.org white-list](http://copyfree.org/standard/licenses) would also be OK.

Thank you very much for all your great contributions to the Nim ecosystem!  :+1:

**Comment by andreaferretti** [comment]
Hello @lbmn the Apache license is what we have as a standard at work for open source contributions, and keeping it in personal projects allows me to transition them to work projects should interest in them arise. I think it is permissive enough by any reasonable standard, so I am not planning to change it.

Thank you for your interest!
